/home/emir/Downloads/loandra/solver/code/MaxSAT.o /home/emir/Downloads/loandra/solver/code/MaxSAT.or /home/emir/Downloads/loandra/solver/code/MaxSAT.od /home/emir/Downloads/loandra/solver/code/MaxSAT.op: /home/emir/Downloads/loandra/solver/code/MaxSAT.cc \
 /home/emir/Downloads/loandra/solver/code/MaxSAT.h \
 /home/emir/Downloads/loandra/solver/code/solvers/glucose4.1/core/Solver.h \
 /home/emir/Downloads/loandra/solver/code/solvers/glucose4.1/mtl/Heap.h \
 /home/emir/Downloads/loandra/solver/code/solvers/glucose4.1/mtl/Vec.h \
 /home/emir/Downloads/loandra/solver/code/solvers/glucose4.1/mtl/IntTypes.h \
 /home/emir/Downloads/loandra/solver/code/solvers/glucose4.1/mtl/XAlloc.h \
 /home/emir/Downloads/loandra/solver/code/solvers/glucose4.1/mtl/Alg.h \
 /home/emir/Downloads/loandra/solver/code/solvers/glucose4.1/utils/Options.h \
 /home/emir/Downloads/loandra/solver/code/solvers/glucose4.1/utils/ParseUtils.h \
 /home/emir/Downloads/loandra/solver/code/solvers/glucose4.1/core/SolverTypes.h \
 /home/emir/Downloads/loandra/solver/code/solvers/glucose4.1/mtl/Map.h \
 /home/emir/Downloads/loandra/solver/code/solvers/glucose4.1/mtl/Alloc.h \
 /home/emir/Downloads/loandra/solver/code/solvers/glucose4.1/core/BoundedQueue.h \
 /home/emir/Downloads/loandra/solver/code/solvers/glucose4.1/core/Constants.h \
 /home/emir/Downloads/loandra/solver/code/solvers/glucose4.1/mtl/Clone.h \
 /home/emir/Downloads/loandra/solver/code/solvers/glucose4.1/core/SolverStats.h \
 /home/emir/Downloads/loandra/solver/code/MaxSATFormula.h \
 /home/emir/Downloads/loandra/solver/code/FormulaPB.h \
 /home/emir/Downloads/loandra/solver/code/MaxTypes.h \
 /home/emir/Downloads/loandra/solver/code/solvers/glucose4.1/utils/System.h
/home/emir/Downloads/loandra/solver/code/Encoder.o /home/emir/Downloads/loandra/solver/code/Encoder.or /home/emir/Downloads/loandra/solver/code/Encoder.od /home/emir/Downloads/loandra/solver/code/Encoder.op: /home/emir/Downloads/loandra/solver/code/Encoder.cc \
 /home/emir/Downloads/loandra/solver/code/Encoder.h \
 /home/emir/Downloads/loandra/solver/code/solvers/glucose4.1/core/Solver.h \
 /home/emir/Downloads/loandra/solver/code/solvers/glucose4.1/mtl/Heap.h \
 /home/emir/Downloads/loandra/solver/code/solvers/glucose4.1/mtl/Vec.h \
 /home/emir/Downloads/loandra/solver/code/solvers/glucose4.1/mtl/IntTypes.h \
 /home/emir/Downloads/loandra/solver/code/solvers/glucose4.1/mtl/XAlloc.h \
 /home/emir/Downloads/loandra/solver/code/solvers/glucose4.1/mtl/Alg.h \
 /home/emir/Downloads/loandra/solver/code/solvers/glucose4.1/utils/Options.h \
 /home/emir/Downloads/loandra/solver/code/solvers/glucose4.1/utils/ParseUtils.h \
 /home/emir/Downloads/loandra/solver/code/solvers/glucose4.1/core/SolverTypes.h \
 /home/emir/Downloads/loandra/solver/code/solvers/glucose4.1/mtl/Map.h \
 /home/emir/Downloads/loandra/solver/code/solvers/glucose4.1/mtl/Alloc.h \
 /home/emir/Downloads/loandra/solver/code/solvers/glucose4.1/core/BoundedQueue.h \
 /home/emir/Downloads/loandra/solver/code/solvers/glucose4.1/core/Constants.h \
 /home/emir/Downloads/loandra/solver/code/solvers/glucose4.1/mtl/Clone.h \
 /home/emir/Downloads/loandra/solver/code/solvers/glucose4.1/core/SolverStats.h \
 /home/emir/Downloads/loandra/solver/code/MaxTypes.h \
 /home/emir/Downloads/loandra/solver/code/encodings/Enc_CNetworks.h \
 /home/emir/Downloads/loandra/solver/code/encodings/Encodings.h \
 /home/emir/Downloads/loandra/solver/code/encodings/../MaxTypes.h \
 /home/emir/Downloads/loandra/solver/code/encodings/Enc_GTE.h \
 /home/emir/Downloads/loandra/solver/code/encodings/Enc_Ladder.h \
 /home/emir/Downloads/loandra/solver/code/encodings/Enc_MTotalizer.h \
 /home/emir/Downloads/loandra/solver/code/encodings/Enc_SWC.h \
 /home/emir/Downloads/loandra/solver/code/encodings/Enc_Totalizer.h \
 /home/emir/Downloads/loandra/solver/code/encodings/Enc_Adder.h
/home/emir/Downloads/loandra/solver/code/MaxSAT_Partition.o /home/emir/Downloads/loandra/solver/code/MaxSAT_Partition.or /home/emir/Downloads/loandra/solver/code/MaxSAT_Partition.od /home/emir/Downloads/loandra/solver/code/MaxSAT_Partition.op: \
 /home/emir/Downloads/loandra/solver/code/MaxSAT_Partition.cc \
 /home/emir/Downloads/loandra/solver/code/solvers/glucose4.1/core/SolverTypes.h \
 /home/emir/Downloads/loandra/solver/code/solvers/glucose4.1/mtl/IntTypes.h \
 /home/emir/Downloads/loandra/solver/code/solvers/glucose4.1/mtl/Alg.h \
 /home/emir/Downloads/loandra/solver/code/solvers/glucose4.1/mtl/Vec.h \
 /home/emir/Downloads/loandra/solver/code/solvers/glucose4.1/mtl/XAlloc.h \
 /home/emir/Downloads/loandra/solver/code/solvers/glucose4.1/mtl/Map.h \
 /home/emir/Downloads/loandra/solver/code/solvers/glucose4.1/mtl/Alloc.h \
 /home/emir/Downloads/loandra/solver/code/MaxSAT_Partition.h \
 /home/emir/Downloads/loandra/solver/code/MaxSAT.h \
 /home/emir/Downloads/loandra/solver/code/solvers/glucose4.1/core/Solver.h \
 /home/emir/Downloads/loandra/solver/code/solvers/glucose4.1/mtl/Heap.h \
 /home/emir/Downloads/loandra/solver/code/solvers/glucose4.1/utils/Options.h \
 /home/emir/Downloads/loandra/solver/code/solvers/glucose4.1/utils/ParseUtils.h \
 /home/emir/Downloads/loandra/solver/code/solvers/glucose4.1/core/BoundedQueue.h \
 /home/emir/Downloads/loandra/solver/code/solvers/glucose4.1/core/Constants.h \
 /home/emir/Downloads/loandra/solver/code/solvers/glucose4.1/mtl/Clone.h \
 /home/emir/Downloads/loandra/solver/code/solvers/glucose4.1/core/SolverStats.h \
 /home/emir/Downloads/loandra/solver/code/MaxSATFormula.h \
 /home/emir/Downloads/loandra/solver/code/FormulaPB.h \
 /home/emir/Downloads/loandra/solver/code/MaxTypes.h \
 /home/emir/Downloads/loandra/solver/code/solvers/glucose4.1/utils/System.h \
 /home/emir/Downloads/loandra/solver/code/graph/Graph.h \
 /home/emir/Downloads/loandra/solver/code/graph/Graph_Communities.h \
 /home/emir/Downloads/loandra/solver/code/graph/Graph.h
/home/emir/Downloads/loandra/solver/code/ParserPB.o /home/emir/Downloads/loandra/solver/code/ParserPB.or /home/emir/Downloads/loandra/solver/code/ParserPB.od /home/emir/Downloads/loandra/solver/code/ParserPB.op: /home/emir/Downloads/loandra/solver/code/ParserPB.cc \
 /home/emir/Downloads/loandra/solver/code/ParserPB.h \
 /home/emir/Downloads/loandra/solver/code/MaxSATFormula.h \
 /home/emir/Downloads/loandra/solver/code/solvers/glucose4.1/core/Solver.h \
 /home/emir/Downloads/loandra/solver/code/solvers/glucose4.1/mtl/Heap.h \
 /home/emir/Downloads/loandra/solver/code/solvers/glucose4.1/mtl/Vec.h \
 /home/emir/Downloads/loandra/solver/code/solvers/glucose4.1/mtl/IntTypes.h \
 /home/emir/Downloads/loandra/solver/code/solvers/glucose4.1/mtl/XAlloc.h \
 /home/emir/Downloads/loandra/solver/code/solvers/glucose4.1/mtl/Alg.h \
 /home/emir/Downloads/loandra/solver/code/solvers/glucose4.1/utils/Options.h \
 /home/emir/Downloads/loandra/solver/code/solvers/glucose4.1/utils/ParseUtils.h \
 /home/emir/Downloads/loandra/solver/code/solvers/glucose4.1/core/SolverTypes.h \
 /home/emir/Downloads/loandra/solver/code/solvers/glucose4.1/mtl/Map.h \
 /home/emir/Downloads/loandra/solver/code/solvers/glucose4.1/mtl/Alloc.h \
 /home/emir/Downloads/loandra/solver/code/solvers/glucose4.1/core/BoundedQueue.h \
 /home/emir/Downloads/loandra/solver/code/solvers/glucose4.1/core/Constants.h \
 /home/emir/Downloads/loandra/solver/code/solvers/glucose4.1/mtl/Clone.h \
 /home/emir/Downloads/loandra/solver/code/solvers/glucose4.1/core/SolverStats.h \
 /home/emir/Downloads/loandra/solver/code/FormulaPB.h \
 /home/emir/Downloads/loandra/solver/code/MaxTypes.h
/home/emir/Downloads/loandra/solver/code/MaxSATFormula.o /home/emir/Downloads/loandra/solver/code/MaxSATFormula.or /home/emir/Downloads/loandra/solver/code/MaxSATFormula.od /home/emir/Downloads/loandra/solver/code/MaxSATFormula.op: \
 /home/emir/Downloads/loandra/solver/code/MaxSATFormula.cc \
 /home/emir/Downloads/loandra/solver/code/MaxSATFormula.h \
 /home/emir/Downloads/loandra/solver/code/solvers/glucose4.1/core/Solver.h \
 /home/emir/Downloads/loandra/solver/code/solvers/glucose4.1/mtl/Heap.h \
 /home/emir/Downloads/loandra/solver/code/solvers/glucose4.1/mtl/Vec.h \
 /home/emir/Downloads/loandra/solver/code/solvers/glucose4.1/mtl/IntTypes.h \
 /home/emir/Downloads/loandra/solver/code/solvers/glucose4.1/mtl/XAlloc.h \
 /home/emir/Downloads/loandra/solver/code/solvers/glucose4.1/mtl/Alg.h \
 /home/emir/Downloads/loandra/solver/code/solvers/glucose4.1/utils/Options.h \
 /home/emir/Downloads/loandra/solver/code/solvers/glucose4.1/utils/ParseUtils.h \
 /home/emir/Downloads/loandra/solver/code/solvers/glucose4.1/core/SolverTypes.h \
 /home/emir/Downloads/loandra/solver/code/solvers/glucose4.1/mtl/Map.h \
 /home/emir/Downloads/loandra/solver/code/solvers/glucose4.1/mtl/Alloc.h \
 /home/emir/Downloads/loandra/solver/code/solvers/glucose4.1/core/BoundedQueue.h \
 /home/emir/Downloads/loandra/solver/code/solvers/glucose4.1/core/Constants.h \
 /home/emir/Downloads/loandra/solver/code/solvers/glucose4.1/mtl/Clone.h \
 /home/emir/Downloads/loandra/solver/code/solvers/glucose4.1/core/SolverStats.h \
 /home/emir/Downloads/loandra/solver/code/FormulaPB.h \
 /home/emir/Downloads/loandra/solver/code/MaxTypes.h
/home/emir/Downloads/loandra/solver/code/Main.o /home/emir/Downloads/loandra/solver/code/Main.or /home/emir/Downloads/loandra/solver/code/Main.od /home/emir/Downloads/loandra/solver/code/Main.op: /home/emir/Downloads/loandra/solver/code/Main.cc \
 /home/emir/Downloads/loandra/solver/code/solvers/glucose4.1/utils/Options.h \
 /home/emir/Downloads/loandra/solver/code/solvers/glucose4.1/mtl/IntTypes.h \
 /home/emir/Downloads/loandra/solver/code/solvers/glucose4.1/mtl/Vec.h \
 /home/emir/Downloads/loandra/solver/code/solvers/glucose4.1/mtl/XAlloc.h \
 /home/emir/Downloads/loandra/solver/code/solvers/glucose4.1/utils/ParseUtils.h \
 /home/emir/Downloads/loandra/solver/code/solvers/glucose4.1/utils/System.h \
 /home/emir/Downloads/loandra/solver/code/solvers/glucose4.1/core/Solver.h \
 /home/emir/Downloads/loandra/solver/code/solvers/glucose4.1/mtl/Heap.h \
 /home/emir/Downloads/loandra/solver/code/solvers/glucose4.1/mtl/Alg.h \
 /home/emir/Downloads/loandra/solver/code/solvers/glucose4.1/core/SolverTypes.h \
 /home/emir/Downloads/loandra/solver/code/solvers/glucose4.1/mtl/Map.h \
 /home/emir/Downloads/loandra/solver/code/solvers/glucose4.1/mtl/Alloc.h \
 /home/emir/Downloads/loandra/solver/code/solvers/glucose4.1/core/BoundedQueue.h \
 /home/emir/Downloads/loandra/solver/code/solvers/glucose4.1/core/Constants.h \
 /home/emir/Downloads/loandra/solver/code/solvers/glucose4.1/mtl/Clone.h \
 /home/emir/Downloads/loandra/solver/code/solvers/glucose4.1/core/SolverStats.h \
 /home/emir/Downloads/loandra/solver/code/MaxSAT.h \
 /home/emir/Downloads/loandra/solver/code/MaxSATFormula.h \
 /home/emir/Downloads/loandra/solver/code/FormulaPB.h \
 /home/emir/Downloads/loandra/solver/code/MaxTypes.h \
 /home/emir/Downloads/loandra/solver/code/ParserMaxSAT.h \
 /home/emir/Downloads/loandra/solver/code/ParserPB.h \
 /home/emir/Downloads/loandra/solver/code/algorithms/Alg_LinearSU.h \
 /home/emir/Downloads/loandra/solver/code/algorithms/../Encoder.h \
 /home/emir/Downloads/loandra/solver/code/algorithms/../MaxTypes.h \
 /home/emir/Downloads/loandra/solver/code/algorithms/../encodings/Enc_CNetworks.h \
 /home/emir/Downloads/loandra/solver/code/algorithms/../encodings/Encodings.h \
 /home/emir/Downloads/loandra/solver/code/algorithms/../encodings/../MaxTypes.h \
 /home/emir/Downloads/loandra/solver/code/algorithms/../encodings/Enc_GTE.h \
 /home/emir/Downloads/loandra/solver/code/algorithms/../encodings/Enc_Ladder.h \
 /home/emir/Downloads/loandra/solver/code/algorithms/../encodings/Enc_MTotalizer.h \
 /home/emir/Downloads/loandra/solver/code/algorithms/../encodings/Enc_SWC.h \
 /home/emir/Downloads/loandra/solver/code/algorithms/../encodings/Enc_Totalizer.h \
 /home/emir/Downloads/loandra/solver/code/algorithms/../encodings/Enc_Adder.h \
 /home/emir/Downloads/loandra/solver/code/algorithms/../MaxSAT.h \
 /home/emir/Downloads/loandra/solver/code/algorithms/Alg_MSU3.h \
 /home/emir/Downloads/loandra/solver/code/algorithms/Alg_OLL.h \
 /home/emir/Downloads/loandra/solver/code/algorithms/Alg_PartMSU3.h \
 /home/emir/Downloads/loandra/solver/code/algorithms/../MaxSAT_Partition.h \
 /home/emir/Downloads/loandra/solver/code/algorithms/../MaxSAT.h \
 /home/emir/Downloads/loandra/solver/code/algorithms/../graph/Graph.h \
 /home/emir/Downloads/loandra/solver/code/algorithms/../graph/Graph_Communities.h \
 /home/emir/Downloads/loandra/solver/code/algorithms/../graph/Graph.h \
 /home/emir/Downloads/loandra/solver/code/algorithms/Alg_WBO.h \
 /home/emir/Downloads/loandra/solver/code/algorithms/../MaxTypes.h \
 /home/emir/Downloads/loandra/solver/code/algorithms/Alg_PMRES.h
